import 'models/model.dart';
import 'models/student_model.dart';

List<PaymentItem> itemsFake = [
  PaymentItem(
      name: 'حلقه‌های مسجد',
      description: 'لیست حضور غیاب',
      isPaid: true,
      chapter: '1.pdf'),
  PaymentItem(
      name: 'ثبت حلقه‌ی جدید',
      description: 'حلقه‌های قرآنی ماه مبارک رمضان',
      isPaid: true,
      chapter: '2.pdf'),
  PaymentItem(
      name: 'حسابداری',
      description: 'مخارج مناسبات',
      isPaid: false,
      chapter: '3.pdf'),
  PaymentItem(
      name: 'یادداشت‌ها و مناسبات',
      description: 'یادآوری به همکاران',
      isPaid: false,
      chapter: '4.pdf'),
];
List<StudentModel> studentsFake = [
  StudentModel.fromApp(
      firstName: 'حسن',
      lastName: 'رضایی',
      grade: 6,
      school: 'سعدی',
      mobilePhone: '09000000000',
      score: 0,
      presence: 0,
      nationalCode: '0000000000',
      classCatId: "2",
      id: "0"),
  StudentModel.fromApp(
      firstName: 'محسن',
      lastName: 'صفایی',
      grade: 7,
      school: 'سعدی',
      mobilePhone: '09000000000',
      score: 10,
      presence: 1,
      nationalCode: '0000000000',
      classCatId: "2",
      id:"1"),
  StudentModel.fromApp(
      firstName: 'محمد طه',
      lastName: 'امیر محصل اصلانی',
      grade: 8,
      school: 'بعثت',
      mobilePhone: '09000000000',
      score: 20,
      presence: 2,
      nationalCode: '0000000000',
      classCatId: "3",
      id: "2"),
  StudentModel.fromApp(
      firstName: 'مجتبی ',
      lastName: 'نجاتی',
      grade: 5,
      school: 'مقصودی',
      mobilePhone: '09000000000',
      score: 0,
      presence: 0,
      nationalCode: '0000000000',
      classCatId: "1",
      id: "3"),
  StudentModel.fromApp(
      firstName: 'محمد',
      lastName: 'هادیان',
      grade: 4,
      school: 'ترابی',
      mobilePhone: '09000000000',
      score: 0,
      presence: 0,
      nationalCode: '0000000000',
      classCatId: "0",
      id: "4"),
  StudentModel.fromApp(
      firstName: 'رضا',
      lastName: 'رمضان زاده',
      grade: 4,
      school: 'مقصودی',
      mobilePhone: '09000000000',
      score: 0,
      presence: 0,
      nationalCode: '0000000000',
      classCatId: "0",
      id: "5"),
  StudentModel.fromApp(
      firstName: 'یحیی',
      lastName: 'معلمی',
      grade: 6,
      school: 'سعدی',
      mobilePhone: '09000000000',
      score: 0,
      presence: 0,
      nationalCode: '0000000000',
      classCatId: "0",
      id: "6"),
  StudentModel.fromApp(
      firstName: 'هادی',
      lastName: 'مجیدی',
      grade: 6,
      school: 'سعدی',
      mobilePhone: '09000000000',
      score: 0,
      presence: 0,
      nationalCode: '0000000000',
      classCatId: "0",
      id: "7"),
  StudentModel.fromApp(
      firstName: 'مجید',
      lastName: 'حقیقت',
      grade: 7,
      school: 'بعثت',
      mobilePhone: '09000000000',
      score: 0,
      presence: 0,
      nationalCode: '0000000000',
      classCatId: "2",
      id:" 8"),
  StudentModel.fromApp(
      firstName: 'امیرمحمد',
      lastName: 'محمدی',
      grade: 8,
      school: 'سعدی',
      mobilePhone: '09000000000',
      score: 15,
      presence: 3,
      nationalCode: '0000000000',
      classCatId: "3",
      id: "9"),
];

List<String> gradeOptionsFake = [
  'اول',
  'دوم',
  'سوم',
  'چهارم',
  'پنجم',
  'ششم',
  'هفتم',
  'هشتم',
  'نهم',
  'متوسطه دوم',
];
List<String> classCatOptionsFake = [
  'کودکان',
  'نوجوانان1',
  'نوجوانان2',
  'نوجوانان3'
];
